# Generated by Django 4.1.7 on 2023-03-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(choices=[['u', 'J'], ['u', 'O'], ['e', 'S'], ['b', 'A'], ['u', 'J'], ['e', 'F'], ['e', 'D'], ['a', 'M'], ['a', 'J'], ['o', 'N'], ['g', 'A'], ['a', 'M']], default='Janeiro', max_length=100)),
                ('mes', models.DateField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoEficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eficiencia', models.FloatField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.mes')),
            ],
            options={
                'ordering': ['equipamento'],
            },
        ),
    ]
