# Generated by Django 4.1.7 on 2023-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='title',
            field=models.CharField(choices=[['o', 'N'], ['b', 'A'], ['u', 'J'], ['g', 'A'], ['u', 'J'], ['u', 'O'], ['e', 'F'], ['a', 'M'], ['e', 'D'], ['a', 'M'], ['e', 'S'], ['a', 'J']], default='Janeiro', max_length=100),
        ),
    ]
